### ISSUE TITLE
astilectron-bundler -v flag provided but not defined: -v

### ISSUE THREAD

**Issue by mh-cbon** [asticode/go-astilectron-demo#53]
met this error executing the readme instructions

this is my session

```
go version go1.12.7 linux/amd64
$ go get -u github.com/asticode/go-astilectron-demo/...
# cd /home/mh-cbon/gow/src/github.com/asticode/go-astitools; git pull --ff-only
Depuis https://github.com/asticode/go-astitools
 + 4d3fb45...d157a99 master     -> origin/master  (mise à jour forcée)
 * [nouvelle étiquette] v1.1.0     -> v1.1.0
 * [nouvelle étiquette] v1.2.0     -> v1.2.0
fatal: Pas possible d'avancer rapidement, abandon.
package github.com/asticode/go-astilectron-demo
	imports github.com/asticode/go-astitools/archive: exit status 128
[mh-cbon@Host-001 opencv4] $ go get -u github.com/asticode/go-astitools/archive
# cd /home/mh-cbon/gow/src/github.com/asticode/go-astitools; git pull --ff-only
fatal: Pas possible d'avancer rapidement, abandon.
package github.com/asticode/go-astitools/archive: exit status 128
[mh-cbon@Host-001 opencv4] $ go get -u github.com/asticode/go-astitools
# cd /home/mh-cbon/gow/src/github.com/asticode/go-astitools; git pull --ff-only
fatal: Pas possible d'avancer rapidement, abandon.
package github.com/asticode/go-astitools: exit status 128
[mh-cbon@Host-001 opencv4] $ rm $GOPATH/src/github.com/asticode/go-astilectron-demo/bind.go
[mh-cbon@Host-001 opencv4] $ rm $GOPATH/src/github.com/asticode/go-astitools
rm: impossible de supprimer '/home/mh-cbon/gow/src/github.com/asticode/go-astitools': est un dossier
[mh-cbon@Host-001 opencv4] $ rm $GOPATH/src/github.com/asticode/go-astitools -fr
[mh-cbon@Host-001 opencv4] $ go get -u github.com/asticode/go-astitools
[mh-cbon@Host-001 opencv4] $ go get -u github.com/asticode/go-astilectron-demo/...
# github.com/asticode/go-astilectron-demo
../gow/src/github.com/asticode/go-astilectron-demo/main.go:41:13: undefined: Asset
../gow/src/github.com/asticode/go-astilectron-demo/main.go:42:13: undefined: AssetDir
../gow/src/github.com/asticode/go-astilectron-demo/main.go:84:18: undefined: RestoreAssets
[mh-cbon@Host-001 opencv4] $ rm $GOPATH/src/github.com/asticode/go-astilectron-demo/bind.go
rm: impossible de supprimer '/home/mh-cbon/gow/src/github.com/asticode/go-astilectron-demo/bind.go': Aucun fichier ou dossier de ce type
[mh-cbon@Host-001 opencv4] $ go get -u github.com/asticode/go-astilectron-bundler/...
[mh-cbon@Host-001 opencv4] $ go install github.com/asticode/go-astilectron-bundler/astilectron-bundler
[mh-cbon@Host-001 opencv4] $ cd $GOPATH/src/github.com/asticode/go-astilectron-demo
[mh-cbon@Host-001 go-astilectron-demo] $ astilectron-bundler -v
flag provided but not defined: -v
Usage of astilectron-bundler:
  -a string
    	the astilectron path
  -c string
    	the configuration path
  -d	if set, will add darwin/amd64 to the environments
  -l	if set, will add linux/amd64 to the environments
  -ldflags value
    	extra values to concatenate onto -ldflags, eg X:main.Version=1.0.7
  -logger-app-name string
    	the logger's app name
  -logger-filename string
    	the logger's filename
  -logger-verbose
    	if true, then log level is debug
  -o string
    	the output path
  -w	if set, will add windows/amd64 to the environments

```

**Comment by asticode** [comment]
This is my bad, it should be fixed now. Can you confirm ?

**Comment by ajeecai** [comment]
Have you fixed it? I download the latest bunder and still get error if running with -v

**Comment by asticode** [comment]
The `-v` flag has been removed, you shouldn't use it
